package exception_try_catch;

public class demo {
	public static void main(String[]args)
	{
		System.out.println("the exception we got is :");
		division.divi();
	}

}
